Version 0.3
nabaco/4-in-row pull request #20
Opened 2019-08-06 14:26 UTC by David6114

add choode_action() function to MinimaxAgent via minimax function

2019-08-06 17:02 UTC, levzlotnik requested changes
To be honest - I don't like the design of the function. I would prefer the implementation that is specified in pseudo-code on AIMA, where there are separate functions for `min_value`, `max_value` that call each other recursively, and in the end the `minimax` calls something along the lines of `max(actions, key=min_value)`. Please check out AIMA for a more clear implementation, instead of using a flag to pass around the `minimax` function that inflates the code and makes it look kinda sloppy and hard to understand.

2019-08-06 17:02 UTC, levzlotnik commented on agents/minimax_agents.py
> +                child.applay_action(self, move)
Pretty sure it should be `node.apply_action`

2019-08-06 17:02 UTC, levzlotnik commented on agents/minimax_agents.py
> +            timer = Timer(TIMEOUT, self.timeout_error())
Please use `self.timeout` as was defined in `SearchAgentBase`.
Also, you pass a function to the constructor of `Timer`, not call it. So that would mean `time = Timer(self.timeout, self.timeout_error)`

2019-08-06 17:06 UTC, David6114 commented on agents/minimax_agents.py
> +                child.applay_action(self, move)
Typo....

2019-08-06 19:14 UTC, nabaco approved these changes

2019-08-06 19:16 UTC, nabaco approved these changes

2019-08-07 08:55 UTC, nabaco approved these changes
IMO, the timer should be in choose_action() and not in minimax(). But since it shouldn't impact performance greatly - approving and merging.

2019-08-07 08:56 UTC, merged